"""Add phone_number to Patient

Revision ID: 3fb5f11dc196
Revises: 985136a5d6e2
Create Date: 2024-08-28 13:17:25.498870

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fb5f11dc196'
down_revision: str | None = '985136a5d6e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add the phone_number column with a default value
    op.add_column('patient', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Unknown'))

    # Remove the default value constraint (if you don't want it to apply to future rows)
    op.alter_column('patient', 'phone_number', server_default=None)
    
    # Other changes
    op.alter_column('rxitem', 'expiration',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.drop_column('rxitem', 'drug_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rxitem', sa.Column('drug_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('rxitem', 'expiration',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.drop_column('patient', 'phone_number')
    # ### end Alembic commands ###
