#!/bin/bash

set -x  # Enable debug mode

DATABASE_URL="postgresql://postgres:postgres@db:5432/pharma-db"

# Change to the directory containing the script
cd "$(dirname "$0")"

# Execute all SQL files within a single transaction
psql $DATABASE_URL << EOF
BEGIN;

\i delete_records.sql
\i insert_patients.sql
\i insert_prescribers.sql
\i insert_rxitems.sql
\i insert_prescriptions.sql

COMMIT;
EOF

